In [57]:
import numpy as np
from glob import glob as glob

from cswsims import *
import tensorflow as tf

from matplotlib import pyplot as plt
%matplotlib inline

%load_ext autoreload
%reload_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### basic csw generate path

In [59]:
task = CSWMLTask(1)
path = task.gen_single_path(task.graphA)


### generating many paths
- probability of same graph controled by pr_shift

In [64]:
task = CSWMLTask(1)
num_stories = 5
pr_shift=.5
pathL,graphidL = task.gen_pathL(num_stories,pr_shift)
pathL,graphidL

SHIFTING
SHIFTING


([array([0, 2, 3, 6, 7, 9]),
  array([0, 1, 3, 5, 7, 9]),
  array([0, 2, 3, 6, 7, 9]),
  array([0, 2, 3, 6, 7, 9]),
  array([0, 2, 3, 6, 7, 9])],
 [11, 10, 11, 11, 11])

### formating many paths into single unroll

In [49]:
X,Y = task.dataset_kstories(pathL,graphidL)
for x,y in zip(X.squeeze(),Y.squeeze()):
  print(x,y)
X.shape,Y.shape

10 0
0 2
2 4
4 6
6 8
8 9
9 10
10 0
0 2
2 4
4 6
6 8
8 9
9 10
10 0
0 1
1 3
3 5
5 7
7 9
9 10
10 0
0 1
1 3
3 5
5 7
7 9
9 10
10 0
0 1
1 3
3 5
5 7
7 9
9 10


((1, 35), (1, 35))

### graph building

In [56]:
nstories = 3
depth = 7*nstories
stsize=20
ML = MetaLearner(stsize,depth)


initializing sub01
SGD01
