In [1]:
import numpy as np
from glob import glob as glob

from cswsims import *
import tensorflow as tf

from matplotlib import pyplot as plt
%matplotlib inline

%load_ext autoreload
%reload_ext autoreload
%autoreload 2

/Users/abeukers/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
task = CSWTask()
graph = task.get_graph(.8)
graph[2]

{3: 0.2, 4: 0.8}

In [3]:
graph

{0: {1: 0.5, 2: 0.5},
 1: {3: 0.8, 4: 0.2},
 2: {3: 0.2, 4: 0.8},
 3: {5: 0.8, 6: 0.2},
 4: {5: 0.2, 6: 0.8},
 5: {7: 0.8, 8: 0.2},
 6: {7: 0.2, 8: 0.8},
 7: {9: 1.0},
 8: {9: 1.0}}

In [6]:
path = path = task.gen_single_path(graph)
X,Y = task.dataset_onestory_with_marker(path,10)
X

array([[[10]],

       [[ 0]],

       [[ 1]],

       [[ 3]],

       [[ 6]]])

In [21]:
Xfull = task.Xfull_onestory_det()
Xfull.shape

(4, 3, 1)

In [19]:
L = [[0,10,1,3,5],[0,10,1,3,5]]
Xeval = task.format_Xeval(L)
# print(Xeval.expand_dim())
# Xeval.
# expecting (2,5,1)





array([[[ 0],
        [10],
        [ 1],
        [ 3],
        [ 5]],

       [[ 0],
        [10],
        [ 1],
        [ 3],
        [ 5]]])

In [35]:
filler=20
path = task.gen_single_path(graph)
X,Y = task.dataset_onestory_with_marker(path,filler,5)
for x,y in zip(X,Y):
  print(x,y)

[[ 0]
 [20]
 [ 1]
 [ 3]
 [ 5]] [[20]
 [ 1]
 [ 3]
 [ 5]
 [ 7]]


In [31]:
Y

array([[[20],
        [ 1],
        [ 3],
        [ 5],
        [ 7]]])

In [4]:
Xo,Yo=task.dataset_onesent(path,12)
Xs,Ys = task.dataset_fullstory(path,bptt_depth=3)

TypeError: dataset_fullstory() got an unexpected keyword argument 'bptt_depth'

In [48]:
graph = task.get_graph(0)
path = task.gen_single_path(graph)
path

array([0, 2, 3, 6, 7, 9])

In [57]:
X,Y = task.dataset_fullstory(path,depth=3)
X[0]

array([[2],
       [3],
       [6]])

In [14]:
Xo = task.Xfull_onesent(fillerL=[10,11])
Xs = task.Xfull_fullstory(depth=5)

In [15]:
Xs.shape,Xo.shape

((5, 5, 1), (18, 1, 2))

In [47]:
Xs

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[1],
        [2],
        [3],
        [4],
        [5]],

       [[2],
        [3],
        [4],
        [5],
        [6]],

       [[3],
        [4],
        [5],
        [6],
        [7]],

       [[4],
        [5],
        [6],
        [7],
        [8]]])

In [17]:
Xo

array([[[ 0, 10]],

       [[ 1, 10]],

       [[ 2, 10]],

       [[ 3, 10]],

       [[ 4, 10]],

       [[ 5, 10]],

       [[ 6, 10]],

       [[ 7, 10]],

       [[ 8, 10]],

       [[ 0, 11]],

       [[ 1, 11]],

       [[ 2, 11]],

       [[ 3, 11]],

       [[ 4, 11]],

       [[ 5, 11]],

       [[ 6, 11]],

       [[ 7, 11]],

       [[ 8, 11]]])