In [1]:
import numpy as np
from glob import glob as glob

from cswsims import *
import tensorflow as tf

from matplotlib import pyplot as plt
%matplotlib inline

%load_ext autoreload
%reload_ext autoreload
%autoreload 2

/Users/abeukers/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
task = CSWTask()
graph = task.get_graph(.8)
path = task.gen_single_path(graph)
path

array([0, 2, 4, 6, 7, 9])

### unroll multiple stories
- still need to generate Xeval: multiple sequences of the same story, single switch in the middle, and interleaved. 

In [66]:
pathL = task.gen_pathL(2,graphA,graphB)
pathL

[array([0, 1, 3, 5, 7, 9]), array([0, 1, 4, 5, 8, 9])]

In [5]:
task = CSWTask()
graphA = task.get_graph(1)
graphB = task.get_graph(0)
graphids = [10,11]

num_stories = 2
pathL = task.gen_pathL(num_stories,graphA,graphB)
graphidL =[graphids[i%2] for i in range(num_stories)] 
Xdata,Ydata = task.dataset_kstories_pomdp(pathL,graphidL)
Xdata.shape


depth = num_stories*7
Xdata.shape,depth

((1, 14, 1), 14)

In [26]:
Xdata[:10]

array([[[10],
        [ 0],
        [ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [ 0],
        [ 1],
        [ 4],
        [ 5],
        [ 8],
        [ 9],
        [10],
        [ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [ 9],
        [11],
        [ 0],
        [ 2],
        [ 3],
        [ 6],
        [ 7],
        [ 9],
        [10],
        [ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [ 9],
        [11],
        [ 0],
        [ 2],
        [ 3],
        [ 6],
        [ 7],
        [ 9],
        [10],
        [ 0],
        [ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [ 0],
        [ 1],
        [ 4],
        [ 5],
        [ 8],
        [ 9],
        [10],
        [ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [ 9],
        [11],
        [ 0],
        [ 1],
        [ 4],
        [ 5]]])

In [35]:
num_stories = 2

[10,0,1,3,5,7,9,11,0,2,4,6] # cA+pA cB+pB

depth = 5+(7*(num_stories-1))
depth
len(path),depth

(12, 12)

In [ ]:
pathL = [[]]

In [24]:
task = CSWTask()
graph = task.get_graph(.8)
path = task.gen_single_path(graph)

In [6]:
net = NetGraph(12)
graph_pr = .8
trainer = Trainer(net,graph_pr)

initializing sub01
SGD01


In [7]:
net.xph

<tf.Tensor 'xdata_placeholder:0' shape=(?, 5, 1) dtype=int32>

In [30]:
eval_paths = [[10,0,1,3,5],
              [10,0,2,4,6],
              [11,0,1,4,5],
              [11,0,2,3,6]]

curr = [[55,1]]
net.reinitialize()
pred_data = trainer.main_loop(curr,eval_paths,flushing=False)
yhat_data = pred_data['yhat']

**reinitializing weights** - incremental seeds
reinitializing sub04
curriculum (55, 1)


In [33]:
pred_data[0]['states'].shape

(4, 10, 12)

In [10]:
lstm_size = 2
net1 = NetGraph(lstm_size)
net2 = NetGraph(lstm_size)

initializing sub01
initializing sub01


In [15]:
net1.reinitialize()
net2.reinitialize()

reinitializing sub02
reinitializing sub02


In [16]:
net2.sess.run(net2.graph.get_collection('variables')[0])[:5]

array([[-0.4169984 , -0.05456334],
       [-0.1561228 , -0.08785975],
       [-0.619358  , -0.4651419 ],
       [-0.592899  , -0.5665328 ],
       [ 0.57028115,  0.26700693]], dtype=float32)

In [17]:
net1.sess.run(net1.graph.get_collection('variables')[0])[:5]

array([[-0.4169984 , -0.05456334],
       [-0.1561228 , -0.08785975],
       [-0.619358  , -0.4651419 ],
       [-0.592899  , -0.5665328 ],
       [ 0.57028115,  0.26700693]], dtype=float32)

In [36]:
X,Y = task.dataset_onestory_with_marker(path,filler_id=100,depth=1)
for x,y in zip(X,Y):
  print(x,y)

[[100]] [[0]]
[[0]] [[2]]
[[2]] [[4]]
[[4]] [[6]]
[[6]] [[8]]


In [36]:
lstm_size = 3
net = NetGraph(lstm_size)

In [37]:
graph_pr = .8
trainer = Trainer(net,graph_pr)

In [53]:
curr = [[100,2]]

eval_paths = [[10,0,1,3,5],
              [10,0,2,4,6],
              [11,0,1,4,5],
              [11,0,2,3,6]]

In [54]:
net.reinitialize()
pred_data = trainer.main_loop(curr,eval_paths)
yhat_data = pred_data['yhat']

**reinitializing weights**
curriculum (100, 2)
0 [0. 0. 0.]
0 [ 1.3439864  -1.0531434  -0.29084286]
0 [-1.0753192   1.3326026  -0.26022708]
0 [-1.398508    0.52226096  0.8746749 ]
0 [ 1.2328498  -0.00888661 -1.219993  ]
0 [ 1.3388115  -1.0634521  -0.26518464]
0 [ 1.3507555  -1.032095   -0.30917436]
0 [ 1.365847   -0.9896082  -0.36526912]
0 [-0.8566735   1.411714   -0.55975395]
0 [-1.349266   0.2905919  1.0536368]
0 [ 1.3442461  -1.0407702  -0.29022238]
0 [-1.3719763   1.0343635   0.32738084]
0 [-1.4105659   0.54516363  0.85820603]
0 [ 1.4095652 -0.7498023 -0.6493078]
0 [-1.1818358   1.2866231  -0.10582752]
0 [-0.81950116 -0.55882823  1.3826894 ]
0 [ 1.2185875  -1.1439357  -0.05390945]
0 [ 1.2560624  -1.1095588  -0.12285018]
0 [ 1.3168217  -1.0277015  -0.25184903]
0 [ 1.3049554  -1.0451257  -0.22731242]
0 [ 1.3869504  -0.8618225  -0.46618336]
0 [ 1.073358   -1.2520702   0.17187314]
0 [ 1.2746629  -1.0809605  -0.16910987]
0 [ 1.2871063  -1.0620861  -0.19962645]
0 [ 1.1627231  -1.1932106 