In [ ]:
import numpy as np
from glob import glob as glob

from cswsims import *
from analysis import *
import tensorflow as tf

from matplotlib import pyplot as plt
%matplotlib inline

%load_ext autoreload
%reload_ext autoreload
%autoreload 2

In [5]:
task = CSWTask()
graph = task.get_graph(.8)
graph[2]

{3: 0.2, 4: 0.8}

In [6]:
path = task.gen_single_path(graph)
path

array([0, 1, 3, 6, 8, 9])

In [4]:
Xo,Yo=task.dataset_onesent(path,12)
Xs,Ys = task.dataset_fullstory(path,bptt_depth=3)

TypeError: dataset_fullstory() got an unexpected keyword argument 'bptt_depth'

In [48]:
graph = task.get_graph(0)
path = task.gen_single_path(graph)
path

array([0, 2, 3, 6, 7, 9])

In [57]:
X,Y = task.dataset_fullstory(path,depth=3)
X[0]

array([[2],
       [3],
       [6]])

In [14]:
Xo = task.Xfull_onesent(fillerL=[10,11])
Xs = task.Xfull_fullstory(depth=5)

In [15]:
Xs.shape,Xo.shape

((5, 5, 1), (18, 1, 2))

In [47]:
Xs

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[1],
        [2],
        [3],
        [4],
        [5]],

       [[2],
        [3],
        [4],
        [5],
        [6]],

       [[3],
        [4],
        [5],
        [6],
        [7]],

       [[4],
        [5],
        [6],
        [7],
        [8]]])

In [17]:
Xo

array([[[ 0, 10]],

       [[ 1, 10]],

       [[ 2, 10]],

       [[ 3, 10]],

       [[ 4, 10]],

       [[ 5, 10]],

       [[ 6, 10]],

       [[ 7, 10]],

       [[ 8, 10]],

       [[ 0, 11]],

       [[ 1, 11]],

       [[ 2, 11]],

       [[ 3, 11]],

       [[ 4, 11]],

       [[ 5, 11]],

       [[ 6, 11]],

       [[ 7, 11]],

       [[ 8, 11]]])